In [ ]:
import numpy as np
np.random.randint(low=1,high=1000,size=100)

array([557, 253, 496, 560, 534, 426, 580, 866, 585, 912, 263, 354, 540,
       543, 318, 498, 779, 454, 283, 349, 807, 945, 545, 596, 159, 578,
       509, 347, 100,  65, 613, 753, 947, 544, 301, 930, 758, 613, 592,
        76, 527, 105, 174,  37,  78, 809, 693, 376, 651, 624,  55, 610,
       546, 471, 649, 814, 652, 225, 106, 233, 664,  26, 319, 174, 134,
       123, 651, 842, 342, 654, 678, 162, 825, 121, 964, 312, 813, 631,
       145, 849,  37, 825, 631, 536, 716, 582, 189, 198, 185, 940, 464,
       686,  69, 983, 407, 193, 603, 525, 153, 736])

In [ ]:
np.random.rand(3,2)

array([[0.13590525, 0.76293709],
       [0.63837935, 0.64564827],
       [0.81723663, 0.94461898]])

In [ ]:
import random
random.randint(10,100)

35

In [ ]:
np.random.uniform(0,5,100)

array([1.95560995, 4.09794871, 3.23001198, 1.9259179 , 1.99988898,
       0.42043426, 1.19502662, 0.88558298, 2.74917771, 2.18050731,
       1.43778524, 3.64742454, 1.93357332, 0.69142539, 0.40544286,
       2.32881665, 4.6580003 , 2.35494196, 1.99397269, 0.57661232,
       2.89623949, 2.21145287, 0.48091336, 2.64389933, 1.72487261,
       4.92870881, 1.83657417, 3.9362248 , 2.29033683, 2.84687175,
       4.79445657, 2.58815056, 0.56269275, 3.73249194, 0.95704588,
       0.57369922, 0.14578362, 1.37927263, 1.69012585, 3.72084116,
       0.28497692, 0.53866101, 2.43656037, 4.79553388, 2.41987944,
       1.36329853, 2.13246035, 3.852019  , 0.75847858, 4.82244376,
       2.1630725 , 0.91424003, 4.17114405, 4.68539435, 3.06485651,
       3.3785905 , 1.99559464, 3.71819469, 1.70954716, 3.40326422,
       3.85599147, 4.94105374, 2.82284029, 3.59392333, 0.96960664,
       3.11905222, 0.54154967, 0.52025929, 3.55155153, 2.20104023,
       2.49256939, 3.32806058, 4.39231593, 4.17274144, 2.98496068,
       1.44375482, 2.2591319 , 1.50752543, 3.05064614, 2.57782356,
       0.84837638, 1.9780643 , 2.08399034, 0.97950295, 4.37733149,
       0.40996861, 3.72573542, 1.91151003, 4.79430225, 3.78339768,
       2.72501557, 0.67576229, 3.35607455, 2.20614032, 0.55033273,
       2.68999928, 2.00658906, 1.45901311, 3.37158614, 3.89681497])

In [ ]:
np.random.normal(25,5,50)

array([38.30305693, 30.4410169 , 27.57650023, 17.57298078, 25.00408557,
       19.007201  , 24.30356038, 18.47235854, 20.55136613, 17.62719048,
       28.65904793, 25.49356741, 28.79406481, 33.73514908, 24.08888307,
       26.27926577, 24.80747875, 20.90969745, 27.97820276, 20.70051494,
       17.52489711, 17.77758588, 20.77295186, 28.00293799, 23.59400021,
       27.81241098, 26.37031963, 23.96935031, 26.45845683, 19.34008702,
       29.00161523, 19.20786258, 21.08519552, 26.30409414, 27.69071277,
       20.79730168, 26.97140116, 25.80161577, 21.66828858, 23.03380254,
       32.90287713, 26.85019622, 24.5708082 , 39.02715914, 28.00903843,
       33.07587992, 29.00548536, 25.0790885 , 18.69018125, 22.8632505 ])

In [ ]:
np.random.binomial(1,0.95,100)
hel

NameError: name 'hel' is not defined

In [ ]:
from scipy.stats import binom
binom.pmf(2,2,0.5)
#first argument is value

In [ ]:
binom.cdf(39,50,0.3)

In [ ]:
#To calculate p(X<70), for X N(loc=60,scale=10)
from scipy.stats import norm
norm.cdf(70,60,10)

np.float64(0.8413447460685429)

In [ ]:
1-norm.cdf(70,60,10)

np.float64(0.15865525393145707)

In [ ]:
norm.cdf(680,711,29)

np.float64(0.14254260383881612)

In [ ]:
norm.cdf(740,711,29)-norm.cdf(640,711,29)

np.float64(0.8341676606756001)

In [ ]:
import pandas as pd
df1=pd.read_csv("BEML.csv")
df2=pd.read_csv("GLAXO.csv")
df1

,Date,Open,High,Low,Last,Close,Total Trade Quantity,Turnover (Lacs)
0,2010-01-04,1121.00,1151.00,1121.00,1134.00,1135.60,101651.0,1157.18
1,2010-01-05,1146.80,1149.00,1128.75,1135.00,1134.60,59504.0,676.47
2,2010-01-06,1140.00,1164.25,1130.05,1137.00,1139.60,128908.0,1482.84
3,2010-01-07,1142.00,1159.40,1119.20,1141.00,1144.15,117871.0,1352.98
4,2010-01-08,1156.00,1172.00,1140.00,1141.20,1144.05,170063.0,1971.42
...,...,...,...,...,...,...,...,...
1734,2016-12-26,965.00,965.05,935.00,950.10,950.25,398696.0,3783.63
1735,2016-12-27,960.70,989.00,952.35,974.00,975.70,808561.0,7885.14
1736,2016-12-28,980.75,985.00,970.15,977.00,974.40,367041.0,3592.49
1737,2016-12-29,977.10,997.95,974.55,985.15,986.05,555233.0,5489.14
1738,2016-12-30,986.00,1006.95,985.90,1004.00,1000.60,460675.0,4606.48

In [ ]:
df2

,Date,Open,High,Low,Last,Close,Total Trade Quantity,Turnover (Lacs)
0,2010-01-04,1613.00,1629.10,1602.00,1629.0,1625.65,9365.0,151.74
1,2010-01-05,1639.95,1639.95,1611.05,1620.0,1616.80,38148.0,622.58
2,2010-01-06,1618.00,1644.00,1617.00,1639.0,1638.50,36519.0,595.09
3,2010-01-07,1645.00,1654.00,1636.00,1648.0,1648.70,12809.0,211.00
4,2010-01-08,1650.00,1650.00,1626.55,1640.0,1639.80,28035.0,459.11
...,...,...,...,...,...,...,...,...
1734,2016-12-26,2703.00,2740.00,2677.00,2715.0,2723.50,3953.0,107.15
1735,2016-12-27,2722.95,2725.00,2683.00,2692.0,2701.75,10600.0,286.10
1736,2016-12-28,2701.75,2718.00,2690.00,2698.0,2702.15,6050.0,163.44
1737,2016-12-29,2702.05,2739.00,2691.95,2710.0,2727.90,7649.0,207.87
1738,2016-12-30,2730.00,2740.45,2705.00,2730.0,2729.80,6513.0,177.65

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns